import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Layouts/Navbar";
import TanstackProvider from "@/providers/TanstackProvider";
import Footer from "@/Components/Layouts/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full md:max-w-10/12 mx-auto">
          <Navbar></Navbar>
        </header>
        <TanstackProvider>
          <main className="w-full md:max-w-10/12 mx-auto min-h-[90vh]">
            {children}
          </main>
        </TanstackProvider>
        <div>
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
